password = [
    48,
    48,
    116,
    71,
    101,
    117,
    117,
    75,
    115,
    97,
    78,
    49,
    74,
    53,
    106,
    115,
    122,
    75,
    98,
    56,
    65,
    102,
    120,
    109,
    104,
    89,
    50,
    104,
    54,
    52,
    122,
    101,
    79,
    101,
    111,
    76,
    48,
    113,
    105,
    54,
    73,
    77,
    65,
    78,
    56,
    86,
    47,
    89,
    118,
    76,
    119,
    80,
    53,
    88,
    121,
    70,
    104,
    48,
    71,
    68,
    104,
    43,
    118,
    103,
    79,
    81,
]
size = [
    0,
    0,
    0,
    0,
]
size_ft = [
    0,
    0,
    0,
    0,
]
size_pf = [
    0,
    0,
    0,
    0,
]
view_style = 'adaptive'
scroll_style = 'scrollauto'
image_quality = 'balanced'
custom_image_quality = [50]
show_remote_cursor = false
lock_after_session_end = false
privacy_mode = false
allow_swap_key = false
port_forwards = []
direct_failures = 1
disable_audio = false
disable_clipboard = false
enable-file-copy-paste = true
show_quality_monitor = false
follow_remote_cursor = false
follow_remote_window = false
keyboard_mode = 'map'
view_only = false
sync-init-clipboard = false

[options]
codec-preference = 'auto'
i444 = ''
swap-left-right-mouse = ''
zoom-cursor = ''
custom-fps = '30'
touch-mode = ''
remote-menubar-drag-x = '0.5032818960615529'

[ui_flutter]

[info]
username = 'mosys'
hostname = 'stephenlaptop'
platform = 'Windows'

[transfer]
write_jobs = []
read_jobs = []
